name: Scrape Flexport Tariffs

# This workflow can be triggered via GitHub API
on:
  workflow_dispatch:
    inputs:
      hts_codes:
        description: 'JSON array of HTS codes (e.g., ["2940.00.6000","2936.27.0000"])'
        required: true
        type: string
      webhook_url:
        description: 'Custom webhook URL (optional - defaults to n8n webhook)'
        required: false
        type: string
        default: 'https://primary-production-f021.up.railway.app/webhook/7b6c881e-77bc-4c8c-b233-a774cc4c66f3'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright httpx
      
      - name: Install Playwright browsers
        run: |
          playwright install chromium
          playwright install-deps chromium
      
      - name: Validate HTS codes input
        id: validate
        env:
          HTS_CODES_INPUT: ${{ inputs.hts_codes }}
        run: |
          echo "Validating HTS codes..."
          python -c "import json, os; codes = json.loads(os.environ['HTS_CODES_INPUT']); print(f'Valid: {len(codes)} codes')"
      
      - name: Run scraper
        env:
          HTS_CODES: ${{ inputs.hts_codes }}
          WEBHOOK_URL: ${{ inputs.webhook_url }}
        run: |
          python scraper.py
      
      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tariff-results
          path: results.json
          retention-days: 7
      
      - name: Print summary
        if: always()
        run: |
          if [ -f results.json ]; then
            echo "=== Scraping Summary ==="
            python -c "import json; data = json.load(open('results.json')); print(f\"Total: {data['total_codes']}\nSuccessful: {data['successful']}\nFailed: {data['failed']}\")"
          else
            echo "No results file found"
          fi
